Repository zachj112/CEN3031-Project, pull requests merged in 2024-04, with the labels that each got.

#9 UFSS 6 and UFSS 19
  registration/__pycache__/__init__.cpython-39.pyc
  registration/__pycache__/admin.cpython-39.pyc
  registration/__pycache__/apps.cpython-39.pyc
  registration/__pycache__/forms.cpython-39.pyc
  registration/__pycache__/models.cpython-39.pyc
  registration/__pycache__/signals.cpython-39.pyc
  registration/__pycache__/urls.cpython-39.pyc
  registration/__pycache__/views.cpython-39.pyc
  registration/migrations/__pycache__/__init__.cpython-39.pyc
  registration/templates/registration/register.html
  static/images/home-uf-banner.jfif
  static/images/register-background.jfif
  static/images/swamp-services-logo.png
  static/images/uf-home-banner2.jfif
  templates/blog-listing.html
  templates/footer.html
  templates/forum-main.html
  templates/header.html
  templates/topic-detail.html
  templates/user-post.html
Labels: enhancement

#14 Main-reset
  templates/header.html
Labels: cleanup

#13 UFSS-52
  templates/forum-main.html
  templates/topic-detail.html
Labels: enhancement

#22 Invisible reg password
  registration/forms.py
Labels: optional change

#23 Overflow and point bug
  forum/models.py
  static/css/amdesk.min.css
  static/css/custom.css
  templates/forum-main.html
  templates/header.html
  templates/topic-detail.html
  templates/user-dashboard.html
  templates/user-post.html
Labels: bug fix

#24 pushing bio and accept answer features
  CommunityApp/__pycache__/settings.cpython-311.pyc
  CommunityApp/__pycache__/urls.cpython-311.pyc
  CommunityApp/settings.py
  CommunityApp/urls.py
  CommunityApp/wsgi.py
  forum/migrations/0001_initial.py
  forum/migrations/0002_alter_userpost_title.py
  forum/migrations/0003_auto_20240420_2241.py
  forum/models.py
  forum/urls.py
  forum/views.py
  registration/forms.py
  registration/templates/registration/profile.html
  static/css/custom.css
  templates/base.html
  templates/blog-detail.html
  templates/blog-listing.html
  templates/footer.html
  templates/search-result.html
  templates/topic-detail.html
Labels: enhancement, bug fix

#26 Reworked open close post html, mods only open close implemented
  forum/migrations/0004_userpost_is_open.py
  forum/models.py
  forum/urls.py
  forum/views.py
  templates/topic-detail.html
Labels: enhancement

#27 sorting feature (partial, but working state)
  forum/models.py
  forum/views.py
  templates/forum-main.html
Labels: bug, enhancement, optional change

#30 points adding and deducting
  forum/views.py
Labels: enhancement, bug fix

#33 added comments into our code
  Project Report.pdf
  README.md
  forum/__pycache__/__init__.cpython-311.pyc
  forum/__pycache__/admin.cpython-311.pyc
  forum/__pycache__/apps.cpython-311.pyc
  forum/__pycache__/forms.cpython-311.pyc
  forum/__pycache__/models.cpython-311.pyc
  forum/__pycache__/urls.cpython-311.pyc
  forum/__pycache__/views.cpython-311.pyc
  forum/admin.py
  forum/apps.py
  forum/forms.py
  forum/migrations/0005_auto_20240423_2137.py
  forum/migrations/__pycache__/0001_initial.cpython-311.pyc
  forum/migrations/__pycache__/0003_auto_20240414_0123.cpython-311.pyc
  forum/migrations/__pycache__/__init__.cpython-311.pyc
  forum/models.py
  forum/urls.py
  forum/views.py
  manage.py
  registration/apps.py
  registration/tests.py
  registration/urls.py
  static/css/custom.css
  static/images/v3_0029453.jpg
  static/images/v3_0098796.jpg
  static/images/v3_0186168.jpg
  static/images/v3_0236147.jpg
  static/images/v3_0369727.jpg
  static/images/v3_0388432.jpg
  static/images/v3_0394877.jpg
  static/images/v3_0436475.jpg
  static/images/v3_0514622.jpg
  static/images/v3_0565611.jpg
  static/images/v3_0573082.jpg
  static/images/v3_0621270.jpg
  static/images/v3_0635333.jpg
  static/images/v3_0773164.jpg
  static/images/v3_0773227.jpg
  static/images/v3_0896814.jpg
  static/images/v3_0956561.jpg
  templates/accept_job_posting.html
  templates/base.html
  templates/blog-detail.html
  templates/blog-listing.html
  templates/footer.html
  templates/forum-main.html
  templates/header.html
  templates/search-result.html
  templates/topic-detail.html
  templates/user-dashboard.html
  templates/user-post.html
Labels: documentation, cleanup

#34 Update README.md
  README.md
Labels: documentation, bug fix
